# Generated by Django 2.2.10 on 2022-03-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220110_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='update_file',
            field=models.FileField(blank=True, null=True, upload_to='media/task'),
        ),
    ]
