# Generated by Django 3.2.13 on 2022-10-19 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_self_taskcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_taskcomment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.self_task'),
        ),
    ]
